Cleanup and stabilization for TUT tracker
Kitware/kwiver pull request #1084
Opened 2020-09-30 15:14 UTC by neal-siekierski

This is the first round of changes to the TUT tracker (`srnn_tracker`) extracted from the publicly released code at `dev/tut-tracker-prr-20200716`. The main addition is basic homography-based stabilization, but there's also some reformatting, refactoring, and bug fixes.

The consumer-visible changes are then:
- `srnn_tracker` now has an optional input port `homography_src_to_ref` that it uses to do tracking in a stabilized coordinate space if present
- Tracks should no longer acquire two new states in a single frame under certain circumstances
- The first-pass IoU tracking should now work as intended

2020-10-20 13:30 UTC, linus-sherrill commented
Is this ready to go? I'm not the best to review all the python changes, so could somebody else approve.

2020-11-25 17:30 UTC, linus-sherrill commented
Is this ready to merge? I am not the best reviewer for the python changes.

2020-12-02 13:34 UTC, dstoup commented
I added some python reviewers so we can get good feedback.

2020-12-02 15:36 UTC, tao558 requested changes

2020-12-02 15:48 UTC, neal-siekierski commented on python/kwiver/sprokit/processes/pytorch/utils/track.py
>  class track_state(object):
The underlying concepts are certainly similar, but what's done here isn't trivially rewritable in terms of the `vital` types as I understand it. #1075 goes into more detail about some of what might need to happen and also applies to the current state of `master`.

2020-12-03 19:24 UTC, tao558 approved these changes

2020-12-03 19:26 UTC, tao558 commented
Approved but I'd recommend still getting input from the other Python folks

2020-12-03 19:54 UTC, Erotemic reviewed
Looks pretty reasonable to me. The code seems reasonably clean. I mainly verified high-level items, I didn't look in depth at the logic.

2020-12-03 19:54 UTC, Erotemic commented on python/kwiver/sprokit/processes/pytorch/utils/iou_tracker.py
> +                del track_state_list[track_state_list.index(match)]
`track_state_list.remove(match)` is faster and more readable. 

Benchmark for evidence in favor of my faster claim:

```python
        import random
        max_list_size = 1000
        max_item_size = int(2 ** 32)

        import timerit
        ti = timerit.Timerit(1000, bestof=10, verbose=2)

        rng = random.Random(0)
        for timer in ti.reset('using remove'):
            list_size = rng.randint(1, max_list_size)
            items = [rng.randint(0, max_item_size) for _ in range(list_size)]
            remove_index = rng.randint(0, list_size - 1)
            remove_item = items[remove_index]
            with timer:
                items.remove(remove_item)

        rng = random.Random(0)
        for timer in ti.reset('using del'):
            list_size = rng.randint(1, max_list_size)
            items = [rng.randint(0, max_item_size) for _ in range(list_size)]
            remove_index = rng.randint(0, list_size - 1)
            remove_item = items[remove_index]
            with timer:
                del items[items.index(remove_item)]
```

Results:

```
Timed using remove for: 1000 loops, best of 10
    time per loop: best=0.646 µs, mean=1.216 ± 0.4 µs
Timed using del for: 1000 loops, best of 10
    time per loop: best=0.745 µs, mean=1.300 ± 0.5 µs
```

2020-12-03 19:54 UTC, Erotemic commented on python/kwiver/sprokit/processes/pytorch/srnn_tracker.py
>              print('timestamp =', repr(timestamp))
Should this print statement be a logging statement?

2020-12-03 19:54 UTC, Erotemic commented on python/kwiver/sprokit/processes/pytorch/utils/models.py
> +                model = model.cuda()
Using `.cuda` makes a lot of assumptions. This should at least be `.to(device)` even if device is hard-coded to 0. What would be even better is if the device was able to be specified.

2022-04-12 19:49 UTC, closed without merging