Fixed incorrect klv tag for target elevation
Kitware/kwiver pull request #1143
Opened 2020-11-24 17:57 UTC by chetnieter

Fixed incorrect klv tag for target elevation in klv conversion code.

2020-11-24 18:08 UTC, dstoup approved these changes

2020-11-24 18:50 UTC, linus-sherrill approved these changes

2020-11-24 18:53 UTC, dstoup commented
Two dashboards went down so they are a little backed up, but are running though now and shouldn't be too long for results.

2020-11-24 21:27 UTC, mleotta requested changes
Change looks good, but can you make a comment about the fix in the release notes files (release.txt)?

2020-11-25 14:59 UTC, mleotta approved these changes

2020-11-25 15:57 UTC, merged