Update `average_frames` variance return type
Kitware/kwiver pull request #1214
Opened 2021-02-24 18:31 UTC by russelldj

The current implementation returned the estimated variance as a `vxl_image_view< double >`. Since all other processes in the burnout filtering stack return the same type as the input, which in practice is a `vxl_byte`, this broke the concatenation stage. I'm open to having the concatenation stage do type checking in addition or instead of this update, but if we choose to go this route, I think we should re-evaluate the types of the images returned by many of these filters. At very least I would advocate for making the returned average value also `double`, both for higher precision results and consistency with the variance.

2021-02-24 22:15 UTC, mleotta commented on arrows/vxl/average_frames.cxx
> +      vil_convert_cast( variance, placeholder );
variance may not be very meaningful if cast to a byte, unless it is also scaled up.  e.g. variance for many pixels may be small, like 0-10 grey values.  If we round that to integers it seems like we are losing a lot of information.

2021-02-24 22:39 UTC, mleotta requested changes
okay from a code standpoint, but I worry about converting variance to a byte image, especially if it is not scaled.  How is his variance used?

2021-02-24 22:45 UTC, russelldj commented
> okay from a code standpoint, but I worry about converting variance to a byte image, especially if it is not scaled. How is his variance used?

In the context of Burnout, it's used once as a feature for the classifier. In another portion of the code, it appears to be used to compute whether a history reset should be performed, by computing how many standard deviations the current pixel is from the historical average. However, this option is not enabled by default and I'm not sure it's worth porting.

I'm leaning toward each filter returning whatever type makes the most sense, rather than enforcing that it's the same as the input. It should be trivial to cast, and perhaps scale, the features in the concatenation process. This is especially relevant given the discussion of adding a summation filter. It seems extremely dangerous to have this filter both take and receive a `byte` since it would probably very quickly overflow.

2021-02-25 03:09 UTC, mleotta commented
If I remember correctly, this "variance" is not actually variance but something closer to sum of squared differences so it grows just like the sum image.  I was worried about rounding errors, but now I'm worried about overflow.  In general, there are many computed features extracted from the image that wouldn't work well as bytes.  It probably makes sense to use `double` or `float` for these.  I wouldn't worry about making everything use bytes until we getting it working.  In the future we may want to optimize for faster processing or less memory usage (after profiling) by switching some of these to bytes, but that has to be done very carefully to make sure we can approximate the same results as with `double`.  We are far from needing such optimizations now.

2021-02-25 13:46 UTC, mwoehlke-kitware commented
Personally, I'd be inclined to always return as whatever is used internally; that's more flexible, and adding an additional conversion step isn't that much more work for the CPU. Conversely, always performing a conversion is work that may not be needed.

2021-02-25 15:35 UTC, russelldj commented
Sounds good.

2021-02-25 15:35 UTC, closed without merging