Fix Python build
Kitware/kwiver pull request #1278
Opened 2021-04-16 16:45 UTC by mwoehlke-kitware

Several places are failing entirely to add the includes for PyBind11, and those places that do are adding them via include_directories. Instead, link the pybind11::pybind11 target in all places that need PyBind11.

This fixes trying to build with a PyBind11 that is not in an include directory that is already being used for some other reason.

2021-04-16 17:42 UTC, johnwparent reviewed
Looks good. This approach seems more in line with the conventions used in the PyBind11 docs as well.

2021-04-16 17:54 UTC, tao558 approved these changes

2021-04-16 18:26 UTC, dstoup requested changes
The only thing that stands out to me is that sometimes pybind11::pybind11 is being added to the PUBLIC link interface and sometime to PRIVATE and when neither is specified, PUBLIC is the default. It would be good if those links were consistent and correct. The general rule I follow is, if your headers are including the headers of the library being linked, they should be PUBLIC since you're adding it to your public interface. If their headers are not in .h file, e.d. .cxx or other, then the links should be PRIVATE so we don't expose the dependencies to user.

2021-04-19 16:03 UTC, mwoehlke-kitware commented
@dstoup, I think for most of the python bindings, the distinction is academic, as these are expected to be leaf targets. I did, however, tweak one spot so that `${PYTHON_LIBRARIES}` and `pybind11::pybind11` always have the same (`PUBLIC`/`PRIVATE`) linkage.

Are you asking me to also audit the linkage of `${PYTHON_LIBRARIES}` everywhere?

2021-04-19 16:14 UTC, mwoehlke-kitware commented
Jenkins test this please

2021-04-19 17:12 UTC, dstoup commented
> @dstoup, I think for most of the python bindings, the distinction is academic, as these are expected to be leaf targets. I did, however, tweak one spot so that `${PYTHON_LIBRARIES}` and `pybind11::pybind11` always have the same (`PUBLIC`/`PRIVATE`) linkage.
> 
> Are you asking me to also audit the linkage of `${PYTHON_LIBRARIES}` everywhere?

No, I think if it's not relevant since they are all leaf targets, we can ignore this comment. I made the comment mostly because it's a touch confusing to have such inconsistency in how the link targets are added but I don't think it's worth any wide-spread audit.

2021-04-19 17:18 UTC, mwoehlke-kitware commented
@dstoup, well, if you note the second commit, you'll see I went ahead and cleaned it up anyway 🙂. BTW, I know for sure `vital_python_util` *should* link PyBind11 as `PUBLIC`, as that is how at least `modules_python` picks it up (note in this PR the removal of `include_directories` for that with no corresponding link change). Also, it seems the purpose of that library is largely or entirely "enhancing" PyBind11 for KWIVER's use, i.e. PyBind11 is clearly part of that library's public API.

2021-04-20 11:41 UTC, dstoup approved these changes
Thanks!

2021-04-20 12:45 UTC, merged