Add manual set of ZeroMQ_INCLUDE_DIR
Kitware/kwiver pull request #1385
Opened 2021-08-17 17:49 UTC by Purg

To go along with "manual" static library discovery.

2021-08-17 17:57 UTC, mleotta requested changes
Please target the release branch for bug fixes

2021-08-17 17:58 UTC, dstoup commented on doc/release-notes/master.txt
> +* Fix mizzing `ZeroMQ_INCLUDE_DIR` set when building statically.
spelling error ... 'mizzing'

2021-08-17 18:00 UTC, Purg commented on doc/release-notes/master.txt
> +* Fix mizzing `ZeroMQ_INCLUDE_DIR` set when building statically.
Oh my. Embarrassing. Will fix with base transition.

2021-08-17 21:00 UTC, tao558 approved these changes

2021-08-20 16:55 UTC, Purg commented
Checking back in. This is now based on release and has a positive review from @tao558. What's the next action here / who's responsible for merging?

2021-08-20 17:45 UTC, merged