Added tag 124, positioning method source
Kitware/kwiver pull request #1506
Opened 2022-01-12 17:13 UTC by hdefazio

2022-01-12 17:14 UTC, hdefazio commented
@daniel-riehm PTAL

2022-01-12 17:28 UTC, daniel-riehm requested changes

2022-01-12 17:28 UTC, daniel-riehm commented on arrows/klv/klv_0601.h
> +  KLV_0601_POSITIONING_METHOD_SOURCE_ON_BOARD_INERTIAL_NAVIGATION_SYSTEM,
```suggestion
  KLV_0601_POSITIONING_METHOD_SOURCE_ON_BOARD_INS,
```
INS is a common abbreviation, so we can save a few keystrokes

2022-01-12 17:28 UTC, daniel-riehm commented on arrows/klv/klv_0601.h
> +operator<<( std::ostream& os, klv_0601_positioning_method_source value );
Declaration looks fine, but I don't see a definition anywhere

2022-01-12 17:28 UTC, daniel-riehm commented on arrows/klv/tests/test_klv_0601.cxx
> +  { KLV_0601_POSITIONING_METHOD_SOURCE,        uint64_t{ 3 } },
I would suggest making this more explicit (using `1 << ENUM | ...`), to match the `KLV_0601_GENERIC_FLAG_DATA` entry on lines 78-81.

2022-01-12 19:28 UTC, daniel-riehm commented on arrows/klv/klv_0601.cxx
> +    "BeiDou-2" };
You'll need one more here at the end: `"Unknown Positioning Method Source Bit"`. The`min` on the next line clamps any numbers outside the valid range to `ENUM_END`, so those will all get that `"Unknown"` string.

2022-01-12 21:02 UTC, daniel-riehm commented on arrows/klv/klv_0601.h
> +enum KWIVER_ALGO_KLV_EXPORT klv_0601_positioning_method_source
One more thing I missed the first time through:
```suggestion
enum KWIVER_ALGO_KLV_EXPORT klv_0601_positioning_method_source_bit
```
And edit the enums too (e.g. `...SOURCE_BIT_GPS`), to be consistent with `generic_flag_data_bit`, marking these as bit indices and not simple numeric values.

2022-01-13 15:30 UTC, daniel-riehm approved these changes

2022-01-13 17:16 UTC, merged