Update pointcloud_io interface
Kitware/kwiver pull request #1542
Opened 2022-03-16 19:38 UTC by willdunklin

Updated use of pointcloud_io interface to follow standard practices. Fixed bug with pointcloud_io failing to save filepath that does not exist yet.

2022-03-16 20:23 UTC, mleotta requested changes

2022-03-16 20:23 UTC, mleotta commented on CMake/kwiver_config.h.in
> -#cmakedefine KWIVER_ENABLE_PDAL
We can probably just delete this whole file now that it is empty and not used.

2022-03-16 20:23 UTC, mleotta commented on arrows/pdal/tests/test_pointcloud_io.cxx
> -  plugin_manager::instance().load_all_plugins();
There is a reason to load the plugins here an not for all tests.  Other than this special "create" test, it's probably better to directly instantiate the pdal object in the other tests.  This way if there is a failure in the plugin loading it only impacts one test that is directly testing plugin loading and the other tests will still run.  There is no problem having the PDAL tests directly link to the PDAL arrow library.

2022-03-16 20:23 UTC, mleotta commented on arrows/pdal/tests/test_pointcloud_io.cxx
> +  auto pc_io = kv::algo::pointcloud_io::create("pdal");
See comment above.  Probably better to use direct instantiation for most tests.

2022-03-16 20:23 UTC, mleotta commented on arrows/pdal/tests/test_pointcloud_io.cxx
>  TEST_F(pointcloud_io, save) {
I missed this style issue before.  The KWIVER style is to have each `{` and `}` on a new line.

2022-03-16 20:23 UTC, mleotta commented on arrows/pdal/tests/test_pointcloud_io.cxx
> +  struct _tmp_file_deleter {
Put `{` on a new line

2022-03-16 20:23 UTC, mleotta commented on arrows/pdal/tests/test_pointcloud_io.cxx
> +    ~_tmp_file_deleter() {
Put `{` on a new line

2022-03-16 20:23 UTC, mleotta commented on arrows/pdal/tests/test_pointcloud_io.cxx
>  TEST_F(pointcloud_io, save_landmarks) {
Put `{` on a new line

2022-03-16 20:23 UTC, mleotta commented on arrows/pdal/tests/test_pointcloud_io.cxx
> +  struct _tmp_file_deleter {
Put `{` on a new line

2022-03-16 20:23 UTC, mleotta commented on arrows/pdal/tests/test_pointcloud_io.cxx
> +    ~_tmp_file_deleter() {
Put `{` on a new line

2022-03-18 14:54 UTC, mleotta requested changes
Looks pretty good, but needs checking in a couple places that the `pc_io` was successfully constructed.

2022-03-18 14:54 UTC, mleotta commented on arrows/vtk/applets/color_mesh.cxx
> +    pc_io->set_local_geo_cs(lgcs);
We need a check here that `pc_io` was created successfully and is not null before we try to use it.  You can thrown an exception if `pc_io` is null.

2022-03-18 14:54 UTC, mleotta commented on arrows/vtk/applets/fuse_depth.cxx
> +        pc_io->set_local_geo_cs(lgcs);
We need a check here that `pc_io` was created successfully and is not null before we try to use it.  You can thrown an exception if `pc_io` is null.

2022-03-18 16:07 UTC, mleotta approved these changes
Need to resolve conflicts now that the branch to relocate test data has landed, but otherwise looks good.

2022-03-18 16:39 UTC, mleotta commented
jenkins test this please

2022-03-18 18:05 UTC, willdunklin commented
jenkins test this please

2022-03-18 18:10 UTC, willdunklin commented
jenkins test this please

2022-03-18 18:14 UTC, willdunklin commented
jenkins test this please

2022-03-18 18:39 UTC, mleotta commented
jenkins test this please

2022-03-18 19:19 UTC, mleotta approved these changes

2022-03-18 19:19 UTC, merged