Refactor ST0104 timestamp conversion
Kitware/kwiver pull request #1587
Opened 2022-04-18 19:26 UTC by daniel-riehm

This PR moves the function which converts a ST0104 timestamp string to a UNIX timestamp from vital to the KLV arrow, where it should be. It also newly allows for omission of the `T` in `YYYYMMDD[T]hhmmss`, which is not technically correct, but has been seen in real-world data and is harmless to add.

Additional reviewer: @hdefazio

2022-04-28 03:39 UTC, mleotta approved these changes

2022-04-28 03:41 UTC, mleotta requested changes
We should get in the habit of maintaining release notes.  Can you can a note to master.txt about this change.  Otherwise looks good.

2022-04-28 13:17 UTC, daniel-riehm commented
> We should get in the habit of maintaining release notes. Can you can a note to master.txt about this change.

I would, but looks like `master.txt` currently summarizes all of the KLV overhaul work, since 1.6.0 was 12 months ago. This is a change to code that hasn't appeared in a release yet, so I'm not sure what change in the release notes would be appropriate.

2022-05-04 21:08 UTC, mleotta approved these changes

2022-05-04 21:08 UTC, merged