Add synthetic KLV test videos
Kitware/kwiver pull request #1705
Opened 2022-11-29 16:52 UTC by daniel-riehm

This PR adds five 30-frame test videos with comprehensive ST0601 test data, and FFmpeg input tests to ensure there are no regressions as KLV development continues. Also included is a tweak to the JSON reader to make it report the stream index of the packet when reading, which is necessary for one of the tests.

The data file sizes are interesting here: each video is below 200KB, but the two JSON reference files are 2MB each. Reviewers may opine whether these sizes are a problem; the JSON files could be reduced significantly by removing whitespace and unnecessary field labels, albeit at the cost of readability.

@hdefazio

2022-12-02 21:02 UTC, hdefazio commented
I think during the weekly meeting we decided to zip the large json files?

2023-01-05 18:19 UTC, daniel-riehm commented
I've pushed up changes which store the ground-truth JSON files as compressed versions to bring them under the 1MB file size limit, so the tests will now decompress those when reading them in.

2023-01-11 20:40 UTC, daniel-riehm commented
Windows failure looks unrelate - something in MVG.

2023-01-13 15:15 UTC, daniel-riehm commented
jenkins test this please

2023-01-13 19:19 UTC, daniel-riehm commented
jenkins test this please

2023-01-13 21:07 UTC, chetnieter requested changes
Looks good - just some minor nit-picks. Given the the json files are compressed I don't think their size is a problem.

2023-01-13 21:07 UTC, chetnieter commented on arrows/ffmpeg/tests/test_video_input_ffmpeg_klv.cxx
> +  for( size_t i = 0; i < 30; ++i )
Number of frames common to two tests. Define once?

2023-01-13 22:12 UTC, daniel-riehm commented
Now that the MVG issue has been resolved, looks like there is an actual test failure on Windows related to this PR...

2023-01-18 19:05 UTC, daniel-riehm commented
@chetnieter Are there any further issues?

2023-01-24 21:11 UTC, chetnieter approved these changes

2023-01-24 21:51 UTC, merged