Add compression utilities, use them for KLV JSON
Kitware/kwiver pull request #1707
Opened 2022-12-02 21:04 UTC by daniel-riehm

This PR contains three related commits.

The first commit creates wrapper classes for zlib compression. `bytestream_compressor` is a standalone version, while `compress_[io]stream` are standard-library-compatible `stream` objects which make inserting compression functionality into existing code easy.

The second commit adds compression as a config option to the KLV JSON reader / writer.

The third commit adds a command-line parameter to `dump-klv` to activate this feature.

Once this is merged, the 2MB test files in #1705 can be stored as compressed 250KB files, getting them under the 1MB suggested file size maximum.

@hdefazio

2022-12-14 21:30 UTC, chetnieter requested changes
Looks good. Just a few minor suggested changes.

2022-12-14 21:30 UTC, chetnieter commented on arrows/zlib/tests/test_bytestream_compressor.cxx
> +  EXPECT_EQ( 175, compressed_data.size() );
Maybe define this expected value as a constexpr in case the size of the test data needs to change.

2022-12-14 21:30 UTC, chetnieter commented on arrows/zlib/tests/test_bytestream_compressor.cxx
> +  EXPECT_EQ( 343, compressed_data.size() );
Maybe define expected result as constexpr?

2022-12-15 18:32 UTC, daniel-riehm commented on arrows/core/applets/dump_klv.cxx
> +    ( "compress", "Compress output file. Only available for klv-json." )
That's a good point; a similar thought had been in the back of my mind. But perhaps this is a task for a separate PR?

2022-12-16 19:06 UTC, chetnieter commented on arrows/core/applets/dump_klv.cxx
> +    ( "compress", "Compress output file. Only available for klv-json." )
Dealing with it in a separate PR sounds reasonable to me.

2022-12-16 20:33 UTC, daniel-riehm commented on CMakeLists.txt
> +  OPTION(KWIVER_ENABLE_ZLIB               "Enable Zlib Arrow" ON)
I've added another commit which does this.

2022-12-21 19:41 UTC, chetnieter commented
> @chetnieter Any further issues?

No - looks good to me

2022-12-21 19:41 UTC, chetnieter approved these changes

2022-12-23 16:50 UTC, merged