Add compare-klv applet
Kitware/kwiver pull request #1733
Opened 2023-02-23 21:41 UTC by daniel-riehm

This PR adds the `compare-klv` applet, which will pretty-print any differences found between the KLV contents of two files.

2023-02-23 22:39 UTC, bradh reviewed
If you sort, are you losing context in something like SDCC?

The case I'm thinking about is where the values are the same, but the previous entries (what ST 1010 calls the Refined Source List) are in a different order, so the SDCC doesn't have the same meaning.

2023-02-24 15:33 UTC, daniel-riehm commented
> If you sort, are you losing context in something like SDCC?
> 
> The case I'm thinking about is where the values are the same, but the previous entries (what ST 1010 calls the Refined Source List) are in a different order, so the SDCC doesn't have the same meaning.

Good question. The `klv_1010_sdcc_flp` structure (`arrows/klv/klv_1010.h`) has the (in retrospect, not super well-named) `members` member, which contains the ordered tags of the Refined Source List. Two `klv_1010_sdcc_flp`s do not compare as equal unless their `members` are equal in addition to their actual data. So once an SDCC knows what should come before it, no important information is lost when reordering.

2023-03-03 16:46 UTC, chetnieter requested changes

2023-03-03 16:46 UTC, chetnieter commented on arrows/klv/applets/compare_klv.cxx
> +// Video or JSON file
At the very least I would suggest this interface and its derived classes be in a separate header and source file. I think we should consider moving the interface to an appropriate place in vital and putting the implementations in `arrows/core`. They are pretty light weight but I can see them being useful to other applications or tools.

2023-05-01 18:56 UTC, chetnieter approved these changes
Remove that empty file if it is really there.

2023-05-01 18:56 UTC, chetnieter commented on vital/algo/metadata_stream_from_map_io.h
Empty file or a GitHub quirk that it is still listed?

2023-05-01 19:11 UTC, daniel-riehm commented on vital/algo/metadata_stream_from_map_io.h
Oops - I must have messed up a rebase somewhere.

2023-05-02 21:05 UTC, merged